#
#   Author: Rohith
#   Date: 2015-04-20 12:28:15 +0100 (Mon, 20 Apr 2015)
#
#  vim:ts=2:sw=2:et
#
FROM shayashibara/docker-consul-template-haproxy:latest
MAINTAINER Rohith Jayawardene <gambol99@gmail.com>

ADD haproxy.template /etc/haproxy/haproxy.template
